// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqc3_UYaa3obzzJ_ObJOttNkZqDUOBMgM',
    appId: '1:539034969611:web:5fe13da7e4e8f50dd4c90e',
    messagingSenderId: '539034969611',
    projectId: 'ecommerceapp-be035',
    authDomain: 'ecommerceapp-be035.firebaseapp.com',
    storageBucket: 'ecommerceapp-be035.appspot.com',
    measurementId: 'G-QJ2GNG2GJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOkQREBxq-5OMarj_Du0SFFoymuGXDNI',
    appId: '1:539034969611:android:ca970741340da4e0d4c90e',
    messagingSenderId: '539034969611',
    projectId: 'ecommerceapp-be035',
    storageBucket: 'ecommerceapp-be035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiEaJlurqJ9B8n32EOI5IMq-Us30SSQ9M',
    appId: '1:539034969611:ios:48932296ee284dd8d4c90e',
    messagingSenderId: '539034969611',
    projectId: 'ecommerceapp-be035',
    storageBucket: 'ecommerceapp-be035.appspot.com',
    iosBundleId: 'com.example.ecommerceflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiEaJlurqJ9B8n32EOI5IMq-Us30SSQ9M',
    appId: '1:539034969611:ios:48932296ee284dd8d4c90e',
    messagingSenderId: '539034969611',
    projectId: 'ecommerceapp-be035',
    storageBucket: 'ecommerceapp-be035.appspot.com',
    iosBundleId: 'com.example.ecommerceflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqc3_UYaa3obzzJ_ObJOttNkZqDUOBMgM',
    appId: '1:539034969611:web:14e3ab3ff7a3a98dd4c90e',
    messagingSenderId: '539034969611',
    projectId: 'ecommerceapp-be035',
    authDomain: 'ecommerceapp-be035.firebaseapp.com',
    storageBucket: 'ecommerceapp-be035.appspot.com',
    measurementId: 'G-F91NBCERKS',
  );
}
